version: "3.8"

services:
  pytest-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-pytest-app:latest
    container_name: my-pytest-app-container
    volumes:
      - .:/app
      - reporthtml:/app/reporthtml
    environment:
      - DISPLAY=:99
    command:
      [
        "python3",
        "-m",
        "pytest",
        "-v",
        "--html=reporthtml/report.html",
        "--self-contained-html",
      ]
    tty: true
    networks:
      - pytest-network

networks:
  pytest-network:
    driver: bridge

volumes:
  reporthtml:
